/*=== 1034 - EVENTOS DE FÉRIAS (LOTE 1 - ATÉ DATA CORTE) ===*/
WITH
PARAM AS (
  SELECT DATE '2026-01-19' AS DT_CORTE FROM DUAL
),

/* contratos existentes no lote (admissão <= corte) */
CONTRATOS_OK AS (
  SELECT C.COD_CONTRATO
    FROM V_DADOS_CONTRATO_AVT C
   CROSS JOIN PARAM P
   GROUP BY C.COD_CONTRATO, P.DT_CORTE
  HAVING MIN(NVL(TRUNC(C.DATA_ADMISSAO), DATE '1900-01-01')) <= P.DT_CORTE
),

/* ===== MAPA “OFICIAL” DAS FÉRIAS: 0328 (período + prevista) + 0327 (real) ===== */
VAC_MAP AS (
  SELECT
      C.COD_CONTRATO,
      TRUNC(C.DATA_INICIO_PERIODO)                 AS DATA_INICIO_PERIODO,
      TRUNC(C.DATA_PREVISTA_FERIAS)                AS DATA_PREVISTA_FERIAS,
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) AS DATA_INICIO_FERIAS
  FROM RHFP0328 C
  LEFT JOIN RHFP0327 F
    ON F.COD_CONTRATO = C.COD_CONTRATO
   AND TRUNC(F.DATA_PREVISTA_FERIAS) = TRUNC(C.DATA_PREVISTA_FERIAS)
  CROSS JOIN PARAM P
  WHERE C.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND TRUNC(C.DATA_PREVISTA_FERIAS) <= P.DT_CORTE
    AND F.TIPO_FERIAS <> 'R'
),

/* ===== EVENTOS DA FOLHA DE FÉRIAS (1003/1006) ===== */
EVENTOS_RAW AS (
  SELECT
      A.COD_CONTRATO,
      A.COD_MESTRE_EVENTO,
      EV.COD_EVENTO,
      A.QTDE_VD,
      A.COD_VD,
      NVL(A.VALOR_VD, 0)        AS VALOR_VD,
      TRUNC(B.DATA_REFERENCIA)  AS DATA_REFERENCIA,
      TRUNC(B.DATA_INI_MOV)     AS DATA_INI_MOV,
      TRUNC(B.DATA_FIM_MOV)     AS DATA_FIM_MOV
  FROM RHFP1006 A
  JOIN RHFP1003 B
    ON B.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO
  JOIN RHFP1000 C
    ON C.COD_VD = A.COD_VD
  JOIN (SELECT DISTINCT COD_VD, COD_EVENTO FROM TB_EVENTOS_VD) EV
    ON EV.COD_VD = A.COD_VD
  CROSS JOIN PARAM P
  WHERE B.COD_EVENTO = 15
    AND C.TIPO_VD NOT IN ('B', 'O')
    AND A.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND TRUNC(B.DATA_REFERENCIA) <= P.DT_CORTE
),

/* mata duplicidade do 1006 no mesmo mestre/vd/evento */
EVENTOS AS (
  SELECT
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV,
      SUM(VALOR_VD) AS VALOR_VD
  FROM EVENTOS_RAW
  GROUP BY
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV
),

/* ===== VÍNCULO CORRETO: cálculo -> férias (pela DATA_PREVISTA_FERIAS) ===== */
EV_VAC AS (
  SELECT
      E.*,
      V.DATA_INICIO_PERIODO,
      V.DATA_INICIO_FERIAS
  FROM EVENTOS E
  JOIN VAC_MAP V
    ON V.COD_CONTRATO = E.COD_CONTRATO
   AND V.DATA_PREVISTA_FERIAS = E.DATA_REFERENCIA
),

/* empresa pelo organograma na data do início do período aquisitivo */
ORG_PICK AS (
  SELECT
      X.COD_CONTRATO,
      X.COD_MESTRE_EVENTO,
      X.DATA_INICIO_PERIODO,
      HIST.COD_ORGANOGRAMA
  FROM (SELECT DISTINCT COD_CONTRATO, COD_MESTRE_EVENTO, DATA_INICIO_PERIODO
          FROM EV_VAC) X
  OUTER APPLY (
      SELECT H.COD_ORGANOGRAMA
        FROM (SELECT H.*,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 1
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN 2
                       ELSE 3
                     END AS RK,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 0
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN TRUNC(X.DATA_INICIO_PERIODO) - TRUNC(H.DATA_INICIO)
                       ELSE TRUNC(H.DATA_INICIO) - TRUNC(X.DATA_INICIO_PERIODO)
                     END AS DIST
                FROM RHFP0310 H
               WHERE H.COD_CONTRATO = X.COD_CONTRATO) H
       ORDER BY RK,
                DIST,
                CASE WHEN RK IN (1,2) THEN H.DATA_INICIO END DESC,
                CASE WHEN RK = 3     THEN H.DATA_INICIO END ASC
       FETCH FIRST 1 ROW ONLY
  ) HIST
)

SELECT
    ORG.COD_NIVEL2 AS "codigo_empresa",
    1 AS "tipo_colaborador",
    E.COD_CONTRATO AS "cadastro_colaborador",
    TO_CHAR(E.DATA_INICIO_PERIODO, 'DD/MM/YYYY') AS "data_inicio_periodo_ferias",
    TO_CHAR(E.DATA_INICIO_FERIAS,  'DD/MM/YYYY') AS "data_inicio_ferias",
    1 AS "codigo_tabela_eventos",
    E.COD_EVENTO AS "codigo_evento",
    TO_CHAR(ROUND(NVL(E.QTDE_VD, 0), 2), 'FM9999999990D00') AS "referencia_evento",
    TO_CHAR(ROUND(NVL(E.VALOR_VD, 0), 2), 'FM9999999990D00') AS "valor_evento"
FROM EV_VAC E
JOIN ORG_PICK OP
  ON OP.COD_CONTRATO = E.COD_CONTRATO
 AND OP.COD_MESTRE_EVENTO = E.COD_MESTRE_EVENTO
 AND OP.DATA_INICIO_PERIODO = E.DATA_INICIO_PERIODO
JOIN RHFP0401 ORG
  ON ORG.COD_ORGANOGRAMA = OP.COD_ORGANOGRAMA
WHERE ORG.COD_NIVEL2 IS NOT NULL
--AND E.COD_CONTRATO = 145459
AND E.VALOR_VD <> 0
ORDER BY E.COD_CONTRATO, E.DATA_INICIO_PERIODO, E.DATA_INICIO_FERIAS, E.COD_EVENTO;







/*=== 1034 - EVENTOS DE FÉRIAS (VERSÃO TRANSFERIDOS) ===*/

WITH
PARAM AS (
  SELECT DATE '2026-04-23' AS DT_CORTE FROM DUAL
),

/* contratos existentes no lote (admissão <= corte) */
CONTRATOS_OK AS (
  SELECT C.COD_CONTRATO
    FROM V_DADOS_CONTRATO_AVT C
   CROSS JOIN PARAM P
   GROUP BY C.COD_CONTRATO, P.DT_CORTE
  HAVING MIN(NVL(TRUNC(C.DATA_ADMISSAO), DATE '1900-01-01')) <= P.DT_CORTE
),

/* =========================================================
   MAPA DE REPLICAÇÃO
   ========================================================= */
MAPA_BASE AS (
    SELECT DISTINCT
           M.COD_CONTRATO,
           M.EMPRESA_ORIGEM,
           M.EMPRESA_DESTINO,
           TRUNC(M.DATA_TRANSFERENCIA) AS DATA_TRANSFERENCIA
      FROM GRZ_MAPA_TRANSF_EMPRESA_V2 M
     WHERE M.EMPRESA_ORIGEM  IS NOT NULL
       AND M.EMPRESA_DESTINO IS NOT NULL
       AND M.EMPRESA_ORIGEM <> M.EMPRESA_DESTINO
),

MAPA_STATS AS (
    SELECT X.COD_CONTRATO,
           COUNT(*) AS QT_MOVIMENTOS,
           COUNT(DISTINCT X.EMPRESA) AS QT_EMPRESAS
      FROM (
            SELECT COD_CONTRATO, EMPRESA_ORIGEM  AS EMPRESA FROM MAPA_BASE
            UNION
            SELECT COD_CONTRATO, EMPRESA_DESTINO AS EMPRESA FROM MAPA_BASE
           ) X
     GROUP BY X.COD_CONTRATO
),

MOV_SEQ AS (
    SELECT MB.COD_CONTRATO,
           MB.EMPRESA_ORIGEM,
           MB.EMPRESA_DESTINO,
           MB.DATA_TRANSFERENCIA,
           ROW_NUMBER() OVER (
               PARTITION BY MB.COD_CONTRATO
               ORDER BY MB.DATA_TRANSFERENCIA,
                        MB.EMPRESA_ORIGEM,
                        MB.EMPRESA_DESTINO
           ) AS RN
      FROM MAPA_BASE MB
),

ULTIMA_TRANSF AS (
    SELECT COD_CONTRATO,
           EMPRESA_ORIGEM,
           EMPRESA_DESTINO,
           DATA_TRANSFERENCIA
      FROM (
            SELECT MS.*,
                   ROW_NUMBER() OVER (
                       PARTITION BY MS.COD_CONTRATO
                       ORDER BY MS.DATA_TRANSFERENCIA DESC,
                                MS.RN DESC
                   ) AS RN_ULT
              FROM MOV_SEQ MS
           )
     WHERE RN_ULT = 1
),

PARES_2_EMPRESAS AS (
    SELECT U.COD_CONTRATO,
           U.EMPRESA_ORIGEM,
           U.EMPRESA_DESTINO,
           U.DATA_TRANSFERENCIA
      FROM ULTIMA_TRANSF U
      JOIN MAPA_STATS S
        ON S.COD_CONTRATO = U.COD_CONTRATO
     WHERE S.QT_EMPRESAS = 2
),

PARES_IMEDIATOS_3MAIS AS (
    SELECT M.COD_CONTRATO,
           M.EMPRESA_ORIGEM,
           M.EMPRESA_DESTINO,
           M.DATA_TRANSFERENCIA
      FROM MOV_SEQ M
      JOIN MAPA_STATS S
        ON S.COD_CONTRATO = M.COD_CONTRATO
     WHERE S.QT_EMPRESAS > 2
),

EMPRESAS_ANTERIORES AS (
    SELECT DISTINCT
           CUR.COD_CONTRATO,
           CUR.RN              AS RN_ATUAL,
           ANT.EMPRESA_ORIGEM  AS EMPRESA_ANTERIOR
      FROM MOV_SEQ CUR
      JOIN MOV_SEQ ANT
        ON ANT.COD_CONTRATO = CUR.COD_CONTRATO
       AND ANT.RN < CUR.RN
      JOIN MAPA_STATS S
        ON S.COD_CONTRATO = CUR.COD_CONTRATO
     WHERE S.QT_EMPRESAS > 2

    UNION

    SELECT DISTINCT
           CUR.COD_CONTRATO,
           CUR.RN               AS RN_ATUAL,
           ANT.EMPRESA_DESTINO  AS EMPRESA_ANTERIOR
      FROM MOV_SEQ CUR
      JOIN MOV_SEQ ANT
        ON ANT.COD_CONTRATO = CUR.COD_CONTRATO
       AND ANT.RN < CUR.RN
      JOIN MAPA_STATS S
        ON S.COD_CONTRATO = CUR.COD_CONTRATO
     WHERE S.QT_EMPRESAS > 2
),

PARES_ACUM_3MAIS AS (
    SELECT DISTINCT
           CUR.COD_CONTRATO,
           EA.EMPRESA_ANTERIOR AS EMPRESA_ORIGEM,
           CUR.EMPRESA_DESTINO AS EMPRESA_DESTINO,
           CUR.DATA_TRANSFERENCIA
      FROM MOV_SEQ CUR
      JOIN EMPRESAS_ANTERIORES EA
        ON EA.COD_CONTRATO = CUR.COD_CONTRATO
       AND EA.RN_ATUAL     = CUR.RN
      JOIN MAPA_STATS S
        ON S.COD_CONTRATO = CUR.COD_CONTRATO
     WHERE S.QT_EMPRESAS > 2
       AND EA.EMPRESA_ANTERIOR <> CUR.EMPRESA_DESTINO
),

PARES_3MAIS_BRUTO AS (
    SELECT * FROM PARES_IMEDIATOS_3MAIS
    UNION ALL
    SELECT * FROM PARES_ACUM_3MAIS
),

PARES_3MAIS AS (
    SELECT COD_CONTRATO,
           EMPRESA_ORIGEM,
           EMPRESA_DESTINO,
           DATA_TRANSFERENCIA
      FROM (
            SELECT P.*,
                   ROW_NUMBER() OVER (
                       PARTITION BY P.COD_CONTRATO,
                                    P.EMPRESA_ORIGEM,
                                    P.EMPRESA_DESTINO
                       ORDER BY P.DATA_TRANSFERENCIA DESC
                   ) AS RN_PAR
              FROM PARES_3MAIS_BRUTO P
           )
     WHERE RN_PAR = 1
),

MAPA_FINAL AS (
    SELECT * FROM PARES_2_EMPRESAS
    UNION ALL
    SELECT * FROM PARES_3MAIS
),

/* ===== MAPA “OFICIAL” DAS FÉRIAS: 0328 (período + prevista) + 0327 (real) ===== */
VAC_MAP AS (
  SELECT
      C.COD_CONTRATO,
      TRUNC(C.DATA_INICIO_PERIODO)                      AS DATA_INICIO_PERIODO,
      TRUNC(C.DATA_PREVISTA_FERIAS)                     AS DATA_PREVISTA_FERIAS,
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) AS DATA_INICIO_FERIAS
  FROM RHFP0328 C
  LEFT JOIN RHFP0327 F
    ON F.COD_CONTRATO = C.COD_CONTRATO
   AND TRUNC(F.DATA_PREVISTA_FERIAS) = TRUNC(C.DATA_PREVISTA_FERIAS)
  CROSS JOIN PARAM P
  WHERE C.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND EXISTS (
          SELECT 1
            FROM MAPA_BASE MB
           WHERE MB.COD_CONTRATO = C.COD_CONTRATO
    )
    AND TRUNC(C.DATA_PREVISTA_FERIAS) <= P.DT_CORTE
    AND NVL(F.TIPO_FERIAS, 'N') <> 'R'
),

/* ===== EVENTOS DA FOLHA DE FÉRIAS (1003/1006) ===== */
EVENTOS_RAW AS (
  SELECT
      A.COD_CONTRATO,
      A.COD_MESTRE_EVENTO,
      EV.COD_EVENTO,
      A.QTDE_VD,
      A.COD_VD,
      NVL(A.VALOR_VD, 0)       AS VALOR_VD,
      TRUNC(B.DATA_REFERENCIA) AS DATA_REFERENCIA,
      TRUNC(B.DATA_INI_MOV)    AS DATA_INI_MOV,
      TRUNC(B.DATA_FIM_MOV)    AS DATA_FIM_MOV
  FROM RHFP1006 A
  JOIN RHFP1003 B
    ON B.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO
  JOIN RHFP1000 C
    ON C.COD_VD = A.COD_VD
  JOIN (SELECT DISTINCT COD_VD, COD_EVENTO FROM TB_EVENTOS_VD) EV
    ON EV.COD_VD = A.COD_VD
  CROSS JOIN PARAM P
  WHERE B.COD_EVENTO = 15
    AND C.TIPO_VD NOT IN ('B', 'O')
    AND A.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND EXISTS (
          SELECT 1
            FROM MAPA_BASE MB
           WHERE MB.COD_CONTRATO = A.COD_CONTRATO
    )
    AND TRUNC(B.DATA_REFERENCIA) <= P.DT_CORTE
),

/* mata duplicidade do 1006 no mesmo mestre/vd/evento */
EVENTOS AS (
  SELECT
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV,
      SUM(VALOR_VD) AS VALOR_VD
  FROM EVENTOS_RAW
  GROUP BY
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV
),

/* ===== vínculo cálculo -> férias ===== */
EV_VAC AS (
  SELECT
      E.*,
      V.DATA_INICIO_PERIODO,
      V.DATA_INICIO_FERIAS
  FROM EVENTOS E
  JOIN VAC_MAP V
    ON V.COD_CONTRATO = E.COD_CONTRATO
   AND V.DATA_PREVISTA_FERIAS = E.DATA_REFERENCIA
),

/* empresa da origem pelo organograma na data do início do período aquisitivo */
ORG_PICK AS (
  SELECT
      X.COD_CONTRATO,
      X.COD_MESTRE_EVENTO,
      X.DATA_INICIO_PERIODO,
      HIST.COD_ORGANOGRAMA
  FROM (
      SELECT DISTINCT COD_CONTRATO, COD_MESTRE_EVENTO, DATA_INICIO_PERIODO
        FROM EV_VAC
  ) X
  OUTER APPLY (
      SELECT H.COD_ORGANOGRAMA
        FROM (
              SELECT H.*,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 1
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN 2
                       ELSE 3
                     END AS RK,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 0
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN TRUNC(X.DATA_INICIO_PERIODO) - TRUNC(H.DATA_INICIO)
                       ELSE TRUNC(H.DATA_INICIO) - TRUNC(X.DATA_INICIO_PERIODO)
                     END AS DIST
                FROM RHFP0310 H
               WHERE H.COD_CONTRATO = X.COD_CONTRATO
        ) H
       ORDER BY RK,
                DIST,
                CASE WHEN RK IN (1,2) THEN H.DATA_INICIO END DESC,
                CASE WHEN RK = 3     THEN H.DATA_INICIO END ASC
       FETCH FIRST 1 ROW ONLY
  ) HIST
),

BASE_ORIGEM AS (
    SELECT
        ORG.COD_NIVEL2 AS COD_EMPRESA,
        1 AS TIPO_COLABORADOR,
        E.COD_CONTRATO,
        E.DATA_INICIO_PERIODO,
        E.DATA_INICIO_FERIAS,
        1 AS CODIGO_TABELA_EVENTOS,
        E.COD_EVENTO,
        E.QTDE_VD,
        E.VALOR_VD
    FROM EV_VAC E
    JOIN ORG_PICK OP
      ON OP.COD_CONTRATO = E.COD_CONTRATO
     AND OP.COD_MESTRE_EVENTO = E.COD_MESTRE_EVENTO
     AND OP.DATA_INICIO_PERIODO = E.DATA_INICIO_PERIODO
    JOIN RHFP0401 ORG
      ON ORG.COD_ORGANOGRAMA = OP.COD_ORGANOGRAMA
   WHERE ORG.COD_NIVEL2 IS NOT NULL
),

/* replica origem -> destino */
BASE_REPLICADA AS (
    SELECT
        MF.EMPRESA_DESTINO AS COD_EMPRESA,
        BO.TIPO_COLABORADOR,
        BO.COD_CONTRATO,
        BO.DATA_INICIO_PERIODO,
        BO.DATA_INICIO_FERIAS,
        BO.CODIGO_TABELA_EVENTOS,
        BO.COD_EVENTO,
        BO.QTDE_VD,
        BO.VALOR_VD,
        ROW_NUMBER() OVER (
            PARTITION BY
                MF.EMPRESA_DESTINO,
                BO.COD_CONTRATO,
                BO.DATA_INICIO_PERIODO,
                BO.DATA_INICIO_FERIAS,
                BO.COD_EVENTO,
                NVL(BO.QTDE_VD, 0),
                NVL(BO.VALOR_VD, 0)
            ORDER BY
                MF.DATA_TRANSFERENCIA DESC,
                MF.EMPRESA_ORIGEM DESC
        ) AS RN
    FROM BASE_ORIGEM BO
    JOIN MAPA_FINAL MF
      ON MF.COD_CONTRATO   = BO.COD_CONTRATO
     AND MF.EMPRESA_ORIGEM = BO.COD_EMPRESA
)

SELECT
    COD_EMPRESA AS "codigo_empresa",
    TIPO_COLABORADOR AS "tipo_colaborador",
    COD_CONTRATO AS "cadastro_colaborador",
    TO_CHAR(DATA_INICIO_PERIODO, 'DD/MM/YYYY') AS "data_inicio_periodo_ferias",
    TO_CHAR(DATA_INICIO_FERIAS,  'DD/MM/YYYY') AS "data_inicio_ferias",
    CODIGO_TABELA_EVENTOS AS "codigo_tabela_eventos",
    COD_EVENTO AS "codigo_evento",
    TO_CHAR(ROUND(NVL(QTDE_VD, 0), 2), 'FM9999999990D00') AS "referencia_evento",
    TO_CHAR(ROUND(NVL(VALOR_VD, 0), 2), 'FM9999999990D00') AS "valor_evento"
FROM BASE_REPLICADA
WHERE RN = 1
ORDER BY COD_CONTRATO, COD_EMPRESA, DATA_INICIO_PERIODO, DATA_INICIO_FERIAS, COD_EVENTO;

