/*=== SQL 1034 - EVENTOS / VALORES DE FÉRIAS ===*/
/* VERSÃO OFICIAL RÁPIDA - BASE ANTIGA + REGRA 1033 */

WITH
PARAM AS (
  SELECT DATE '2026-04-23' AS DT_CORTE FROM DUAL
),

/* Contratos admitidos antes da data de corte */
CONTRATOS_OK AS (
  SELECT /*+ MATERIALIZE */
      C.COD_CONTRATO,
      MIN(TRUNC(C.DATA_ADMISSAO)) AS DATA_ADMISSAO,
      MAX(TRUNC(C.DATA_DEMISSAO)) AS DATA_DEMISSAO
  FROM V_DADOS_CONTRATO_AVT C
  CROSS JOIN PARAM P
  GROUP BY C.COD_CONTRATO, P.DT_CORTE
  HAVING MIN(NVL(TRUNC(C.DATA_ADMISSAO), DATE '1900-01-01')) < P.DT_CORTE
),

/* Evita multiplicação pela RHFP0401 */
ORG_UNICO AS (
  SELECT /*+ MATERIALIZE */
      O.COD_ORGANOGRAMA,
      MAX(O.COD_NIVEL2) AS COD_NIVEL2
  FROM RHFP0401 O
  WHERE O.COD_NIVEL2 IS NOT NULL
  GROUP BY O.COD_ORGANOGRAMA
),

/*
  Programações válidas conforme regra do 1033:
  - nasce da RHFP0327;
  - remove TIPO_FERIAS = R;
  - não remove demitido inteiro;
  - remove somente férias depois da demissão.
*/
FERIAS_0327_VALIDA AS (
  SELECT /*+ MATERIALIZE */
      ROWIDTOCHAR(F.ROWID) AS RID_FERIAS,
      F.COD_CONTRATO,
      TRUNC(F.DATA_PREVISTA_FERIAS) AS DATA_PREVISTA_FERIAS,
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) AS DATA_INICIO_FERIAS,
      NVL(F.TIPO_FERIAS, 'N') AS TIPO_FERIAS
  FROM RHFP0327 F
  JOIN CONTRATOS_OK OK
    ON OK.COD_CONTRATO = F.COD_CONTRATO
  WHERE NVL(F.TIPO_FERIAS, 'N') <> 'R'
    AND (
          OK.DATA_DEMISSAO IS NULL
          OR TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) <= TRUNC(OK.DATA_DEMISSAO)
        )
),

/*
  Mapa férias válido:
  usa RHFP0328 apenas para descobrir o período aquisitivo da programação.
  Não cria férias pela 0328.
*/
VAC_MAP_RAW AS (
  SELECT /*+ MATERIALIZE */
      F.RID_FERIAS,
      P.COD_CONTRATO,
      TRUNC(P.DATA_INICIO_PERIODO) AS DATA_INICIO_PERIODO,
      F.DATA_PREVISTA_FERIAS,
      F.DATA_INICIO_FERIAS,

      ROW_NUMBER() OVER (
        PARTITION BY
            P.COD_CONTRATO,
            F.DATA_PREVISTA_FERIAS
        ORDER BY
            TRUNC(P.DATA_INICIO_PERIODO),
            F.DATA_INICIO_FERIAS,
            F.RID_FERIAS
      ) AS RN
  FROM FERIAS_0327_VALIDA F
  JOIN RHFP0328 P
    ON P.COD_CONTRATO = F.COD_CONTRATO
   AND TRUNC(P.DATA_PREVISTA_FERIAS) = F.DATA_PREVISTA_FERIAS
  CROSS JOIN PARAM PA
  WHERE TRUNC(P.DATA_INICIO_PERIODO) < PA.DT_CORTE
),

VAC_MAP AS (
  SELECT /*+ MATERIALIZE */
      RID_FERIAS,
      COD_CONTRATO,
      DATA_INICIO_PERIODO,
      DATA_PREVISTA_FERIAS,
      DATA_INICIO_FERIAS
  FROM VAC_MAP_RAW
  WHERE RN = 1
),

EVENTOS_VD AS (
  SELECT /*+ MATERIALIZE */
      DISTINCT
      COD_VD,
      COD_EVENTO
  FROM TB_EVENTOS_VD
),

/*
  Mantém a estratégia rápida antiga:
  começa pelos eventos reais da folha de férias.
*/
EVENTOS_RAW AS (
  SELECT
      A.COD_CONTRATO,
      A.COD_MESTRE_EVENTO,
      EV.COD_EVENTO,
      ROUND(NVL(A.QTDE_VD, 0), 2) AS QTDE_VD,
      A.COD_VD,
      NVL(A.VALOR_VD, 0) AS VALOR_VD,
      TRUNC(B.DATA_REFERENCIA) AS DATA_REFERENCIA,
      TRUNC(B.DATA_INI_MOV) AS DATA_INI_MOV,
      TRUNC(B.DATA_FIM_MOV) AS DATA_FIM_MOV
  FROM RHFP1006 A
  JOIN RHFP1003 B
    ON B.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO
  JOIN RHFP1000 C
    ON C.COD_VD = A.COD_VD
  JOIN EVENTOS_VD EV
    ON EV.COD_VD = A.COD_VD
  WHERE B.COD_EVENTO = 15
    AND C.TIPO_VD NOT IN ('B', 'O')
    AND NVL(A.VALOR_VD, 0) <> 0
    AND EXISTS (
          SELECT 1
          FROM CONTRATOS_OK OK
          WHERE OK.COD_CONTRATO = A.COD_CONTRATO
        )
),

/* Consolida duplicidade real do 1006 no mesmo mestre/vd/evento */
EVENTOS AS (
  SELECT /*+ MATERIALIZE */
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV,
      SUM(VALOR_VD) AS VALOR_VD
  FROM EVENTOS_RAW
  GROUP BY
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      QTDE_VD,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV
),

/*
  Vínculo cálculo -> programação válida.
  Aqui é onde removemos, de fato, os cálculos de rescisão:
  se a programação não entrou no VAC_MAP, o evento não passa.
*/
EV_VAC AS (
  SELECT /*+ MATERIALIZE */
      E.*,
      V.RID_FERIAS,
      V.DATA_INICIO_PERIODO,
      V.DATA_INICIO_FERIAS
  FROM EVENTOS E
  JOIN VAC_MAP V
    ON V.COD_CONTRATO = E.COD_CONTRATO
   AND V.DATA_PREVISTA_FERIAS = E.DATA_REFERENCIA
),

/* Chaves únicas para resolver empresa */
EV_CHAVES_ORG AS (
  SELECT /*+ MATERIALIZE */
      DISTINCT
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      DATA_INICIO_PERIODO
  FROM EV_VAC
),

/* Empresa pelo organograma na data do início do período aquisitivo */
ORG_CANDIDATOS AS (
  SELECT
      X.COD_CONTRATO,
      X.COD_MESTRE_EVENTO,
      X.DATA_INICIO_PERIODO,
      H.COD_ORGANOGRAMA,

      ROW_NUMBER() OVER (
          PARTITION BY
              X.COD_CONTRATO,
              X.COD_MESTRE_EVENTO,
              X.DATA_INICIO_PERIODO
          ORDER BY
              CASE
                WHEN TRUNC(H.DATA_INICIO) <= X.DATA_INICIO_PERIODO
                 AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= X.DATA_INICIO_PERIODO
                THEN 1

                WHEN TRUNC(H.DATA_INICIO) <= X.DATA_INICIO_PERIODO
                THEN 2

                ELSE 3
              END,

              CASE
                WHEN TRUNC(H.DATA_INICIO) <= X.DATA_INICIO_PERIODO
                 AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= X.DATA_INICIO_PERIODO
                THEN 0

                WHEN TRUNC(H.DATA_INICIO) <= X.DATA_INICIO_PERIODO
                THEN X.DATA_INICIO_PERIODO - TRUNC(H.DATA_INICIO)

                ELSE TRUNC(H.DATA_INICIO) - X.DATA_INICIO_PERIODO
              END,

              CASE
                WHEN TRUNC(H.DATA_INICIO) <= X.DATA_INICIO_PERIODO
                THEN H.DATA_INICIO
              END DESC,

              CASE
                WHEN TRUNC(H.DATA_INICIO) > X.DATA_INICIO_PERIODO
                THEN H.DATA_INICIO
              END ASC
      ) AS RN
  FROM EV_CHAVES_ORG X
  JOIN RHFP0310 H
    ON H.COD_CONTRATO = X.COD_CONTRATO
),

ORG_PICK AS (
  SELECT /*+ MATERIALIZE */
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      DATA_INICIO_PERIODO,
      COD_ORGANOGRAMA
  FROM ORG_CANDIDATOS
  WHERE RN = 1
),

BASE_FINAL AS (
  SELECT
      ORG.COD_NIVEL2 AS CODIGO_EMPRESA,
      E.COD_CONTRATO,
      E.DATA_INICIO_PERIODO,
      E.DATA_INICIO_FERIAS,
      E.COD_EVENTO,
      E.QTDE_VD,
      E.COD_VD,
      E.COD_MESTRE_EVENTO,
      E.VALOR_VD
  FROM EV_VAC E
  JOIN ORG_PICK OP
    ON OP.COD_CONTRATO = E.COD_CONTRATO
   AND OP.COD_MESTRE_EVENTO = E.COD_MESTRE_EVENTO
   AND OP.DATA_INICIO_PERIODO = E.DATA_INICIO_PERIODO
  JOIN ORG_UNICO ORG
    ON ORG.COD_ORGANOGRAMA = OP.COD_ORGANOGRAMA
  WHERE ORG.COD_NIVEL2 IS NOT NULL
    AND NVL(E.VALOR_VD, 0) <> 0
),

/*
  Agrupamento final pela chave exportada.
  Se dois VDs apontarem para o mesmo evento final, soma o valor.
*/
FINAL_AGR AS (
  SELECT
      CODIGO_EMPRESA,
      COD_CONTRATO,
      DATA_INICIO_PERIODO,
      DATA_INICIO_FERIAS,
      COD_EVENTO,
      QTDE_VD,
      SUM(VALOR_VD) AS VALOR_VD
  FROM BASE_FINAL
  GROUP BY
      CODIGO_EMPRESA,
      COD_CONTRATO,
      DATA_INICIO_PERIODO,
      DATA_INICIO_FERIAS,
      COD_EVENTO,
      QTDE_VD
  HAVING ROUND(SUM(VALOR_VD), 2) <> 0
),

EVENTOS_VD AS (
  SELECT DISTINCT
      COD_VD,
      COD_EVENTO
  FROM TB_EVENTOS_VD
),

/*
  Universo esperado:
  eventos de férias que possuem programação válida no 1033.
*/
ESPERADO AS (
  SELECT
      A.COD_CONTRATO,
      TRUNC(P.DATA_INICIO_PERIODO) AS DATA_INICIO_PERIODO,
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) AS DATA_INICIO_FERIAS,
      EV.COD_EVENTO,
      ROUND(NVL(A.QTDE_VD, 0), 2) AS QTDE_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS VALOR_VD
  FROM RHFP1006 A

  JOIN RHFP1003 B
    ON B.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO

  JOIN RHFP1000 VD
    ON VD.COD_VD = A.COD_VD

  JOIN EVENTOS_VD EV
    ON EV.COD_VD = A.COD_VD

  JOIN CONTRATOS_OK OK
    ON OK.COD_CONTRATO = A.COD_CONTRATO

  JOIN RHFP0327 F
    ON F.COD_CONTRATO = A.COD_CONTRATO
   AND TRUNC(F.DATA_PREVISTA_FERIAS) = TRUNC(B.DATA_REFERENCIA)

  JOIN RHFP0328 P
    ON P.COD_CONTRATO = F.COD_CONTRATO
   AND TRUNC(P.DATA_PREVISTA_FERIAS) = TRUNC(F.DATA_PREVISTA_FERIAS)

  CROSS JOIN PARAM PA

  WHERE B.COD_EVENTO = 15
    AND VD.TIPO_VD NOT IN ('B', 'O')
    AND NVL(A.VALOR_VD, 0) <> 0
    AND NVL(F.TIPO_FERIAS, 'N') <> 'R'
    AND TRUNC(P.DATA_INICIO_PERIODO) < PA.DT_CORTE
    AND (
          OK.DATA_DEMISSAO IS NULL
          OR TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) <= TRUNC(OK.DATA_DEMISSAO)
        )

  GROUP BY
      A.COD_CONTRATO,
      TRUNC(P.DATA_INICIO_PERIODO),
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)),
      EV.COD_EVENTO,
      ROUND(NVL(A.QTDE_VD, 0), 2)
),

/*
  Cole aqui o resultado final do 1034 novo,
  sem ORDER BY.
*/
RESULTADO_1034 AS (
  SELECT
      F.CODIGO_EMPRESA AS codigo_empresa,
      1 AS tipo_colaborador,
      F.COD_CONTRATO AS cadastro_colaborador,
      F.DATA_INICIO_PERIODO AS data_inicio_periodo_ferias,
      F.DATA_INICIO_FERIAS AS data_inicio_ferias,
      1 AS codigo_tabela_eventos,
      F.COD_EVENTO AS codigo_evento,
      F.QTDE_VD AS referencia_evento,
      ROUND(F.VALOR_VD, 2) AS valor_evento
  FROM FINAL_AGR F
),

RESULTADO_AGR AS (
  SELECT
      cadastro_colaborador AS COD_CONTRATO,
      data_inicio_periodo_ferias AS DATA_INICIO_PERIODO,
      data_inicio_ferias AS DATA_INICIO_FERIAS,
      codigo_evento AS COD_EVENTO,
      referencia_evento AS QTDE_VD,
      SUM(valor_evento) AS VALOR_VD
  FROM RESULTADO_1034
  GROUP BY
      cadastro_colaborador,
      data_inicio_periodo_ferias,
      data_inicio_ferias,
      codigo_evento,
      referencia_evento
)

SELECT
    F.CODIGO_EMPRESA AS "codigo_empresa",
    1 AS "tipo_colaborador",
    F.COD_CONTRATO AS "cadastro_colaborador",
    TO_CHAR(F.DATA_INICIO_PERIODO, 'DD/MM/YYYY') AS "data_inicio_periodo_ferias",
    TO_CHAR(F.DATA_INICIO_FERIAS,  'DD/MM/YYYY') AS "data_inicio_ferias",
    1 AS "codigo_tabela_eventos",
    F.COD_EVENTO AS "codigo_evento",
    TO_CHAR(F.QTDE_VD, 'FM9999999990D00') AS "referencia_evento",
    TO_CHAR(ROUND(F.VALOR_VD, 2), 'FM9999999990D00') AS "valor_evento"
FROM FINAL_AGR F
ORDER BY
    F.COD_CONTRATO,
    F.DATA_INICIO_PERIODO,
    F.DATA_INICIO_FERIAS,
    F.COD_EVENTO






/*VALIDADOR*/
/*SELECT
    E.COD_CONTRATO,
    E.DATA_INICIO_PERIODO,
    E.DATA_INICIO_FERIAS,
    E.COD_EVENTO,
    E.QTDE_VD,
    ROUND(E.VALOR_VD, 2) AS VALOR_ESPERADO,
    ROUND(NVL(R.VALOR_VD, 0), 2) AS VALOR_RESULTADO,
    ROUND(E.VALOR_VD - NVL(R.VALOR_VD, 0), 2) AS DIFERENCA
FROM ESPERADO E
LEFT JOIN RESULTADO_AGR R
  ON R.COD_CONTRATO = E.COD_CONTRATO
 AND R.DATA_INICIO_PERIODO = E.DATA_INICIO_PERIODO
 AND R.DATA_INICIO_FERIAS = E.DATA_INICIO_FERIAS
 AND R.COD_EVENTO = E.COD_EVENTO
 AND R.QTDE_VD = E.QTDE_VD
WHERE ROUND(NVL(R.VALOR_VD, 0), 2) <> ROUND(E.VALOR_VD, 2)
ORDER BY
    E.COD_CONTRATO,
    E.DATA_INICIO_PERIODO,
    E.DATA_INICIO_FERIAS,
    E.COD_EVENTO;*/