/*=== 1034 - EVENTOS DE FÉRIAS (LOTE 1 - ATÉ DATA CORTE) ===*/
WITH
PARAM AS (
  SELECT DATE '2026-01-19' AS DT_CORTE FROM DUAL
),

/* contratos existentes no lote (admissão <= corte) */
CONTRATOS_OK AS (
  SELECT C.COD_CONTRATO
    FROM V_DADOS_CONTRATO_AVT C
   CROSS JOIN PARAM P
   GROUP BY C.COD_CONTRATO, P.DT_CORTE
  HAVING MIN(NVL(TRUNC(C.DATA_ADMISSAO), DATE '1900-01-01')) <= P.DT_CORTE
),

/* ===== MAPA “OFICIAL” DAS FÉRIAS: 0328 (período + prevista) + 0327 (real) ===== */
VAC_MAP AS (
  SELECT
      C.COD_CONTRATO,
      TRUNC(C.DATA_INICIO_PERIODO)                 AS DATA_INICIO_PERIODO,
      TRUNC(C.DATA_PREVISTA_FERIAS)                AS DATA_PREVISTA_FERIAS,
      TRUNC(NVL(F.DATA_FERIAS, F.DATA_PREVISTA_FERIAS)) AS DATA_INICIO_FERIAS
  FROM RHFP0328 C
  LEFT JOIN RHFP0327 F
    ON F.COD_CONTRATO = C.COD_CONTRATO
   AND TRUNC(F.DATA_PREVISTA_FERIAS) = TRUNC(C.DATA_PREVISTA_FERIAS)
  CROSS JOIN PARAM P
  WHERE C.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND TRUNC(C.DATA_PREVISTA_FERIAS) <= P.DT_CORTE
),

/* ===== EVENTOS DA FOLHA DE FÉRIAS (1003/1006) ===== */
EVENTOS_RAW AS (
  SELECT
      A.COD_CONTRATO,
      A.COD_MESTRE_EVENTO,
      EV.COD_EVENTO,
      A.COD_VD,
      NVL(A.VALOR_VD, 0)        AS VALOR_VD,
      TRUNC(B.DATA_REFERENCIA)  AS DATA_REFERENCIA,
      TRUNC(B.DATA_INI_MOV)     AS DATA_INI_MOV,
      TRUNC(B.DATA_FIM_MOV)     AS DATA_FIM_MOV
  FROM RHFP1006 A
  JOIN RHFP1003 B
    ON B.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO
  JOIN RHFP1000 C
    ON C.COD_VD = A.COD_VD
  JOIN (SELECT DISTINCT COD_VD, COD_EVENTO FROM TB_EVENTOS_VD) EV
    ON EV.COD_VD = A.COD_VD
  CROSS JOIN PARAM P
  WHERE B.COD_EVENTO = 15
    AND C.TIPO_VD NOT IN ('B', 'O')
    AND A.COD_CONTRATO IN (SELECT COD_CONTRATO FROM CONTRATOS_OK)
    AND TRUNC(B.DATA_REFERENCIA) <= P.DT_CORTE
),

/* mata duplicidade do 1006 no mesmo mestre/vd/evento */
EVENTOS AS (
  SELECT
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV,
      SUM(VALOR_VD) AS VALOR_VD
  FROM EVENTOS_RAW
  GROUP BY
      COD_CONTRATO,
      COD_MESTRE_EVENTO,
      COD_EVENTO,
      COD_VD,
      DATA_REFERENCIA,
      DATA_INI_MOV,
      DATA_FIM_MOV
),

/* ===== VÍNCULO CORRETO: cálculo -> férias (pela DATA_PREVISTA_FERIAS) ===== */
EV_VAC AS (
  SELECT
      E.*,
      V.DATA_INICIO_PERIODO,
      V.DATA_INICIO_FERIAS
  FROM EVENTOS E
  JOIN VAC_MAP V
    ON V.COD_CONTRATO = E.COD_CONTRATO
   AND V.DATA_PREVISTA_FERIAS = E.DATA_REFERENCIA
),

/* empresa pelo organograma na data do início do período aquisitivo */
ORG_PICK AS (
  SELECT
      X.COD_CONTRATO,
      X.COD_MESTRE_EVENTO,
      X.DATA_INICIO_PERIODO,
      HIST.COD_ORGANOGRAMA
  FROM (SELECT DISTINCT COD_CONTRATO, COD_MESTRE_EVENTO, DATA_INICIO_PERIODO
          FROM EV_VAC) X
  OUTER APPLY (
      SELECT H.COD_ORGANOGRAMA
        FROM (SELECT H.*,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 1
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN 2
                       ELSE 3
                     END AS RK,
                     CASE
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO)
                        AND TRUNC(NVL(H.DATA_FIM, DATE '9999-12-31')) >= TRUNC(X.DATA_INICIO_PERIODO) THEN 0
                       WHEN TRUNC(H.DATA_INICIO) <= TRUNC(X.DATA_INICIO_PERIODO) THEN TRUNC(X.DATA_INICIO_PERIODO) - TRUNC(H.DATA_INICIO)
                       ELSE TRUNC(H.DATA_INICIO) - TRUNC(X.DATA_INICIO_PERIODO)
                     END AS DIST
                FROM RHFP0310 H
               WHERE H.COD_CONTRATO = X.COD_CONTRATO) H
       ORDER BY RK,
                DIST,
                CASE WHEN RK IN (1,2) THEN H.DATA_INICIO END DESC,
                CASE WHEN RK = 3     THEN H.DATA_INICIO END ASC
       FETCH FIRST 1 ROW ONLY
  ) HIST
)

SELECT
    ORG.COD_NIVEL2 AS "codigo_empresa",
    1 AS "tipo_colaborador",
    E.COD_CONTRATO AS "cadastro_colaborador",
    TO_CHAR(E.DATA_INICIO_PERIODO, 'DD/MM/YYYY') AS "data_inicio_periodo_ferias",
    TO_CHAR(E.DATA_INICIO_FERIAS,  'DD/MM/YYYY') AS "data_inicio_ferias",
    1 AS "codigo_tabela_eventos",
    E.COD_EVENTO AS "codigo_evento",
    0 AS "referencia_evento",
    E.VALOR_VD AS "valor_evento"
FROM EV_VAC E
JOIN ORG_PICK OP
  ON OP.COD_CONTRATO = E.COD_CONTRATO
 AND OP.COD_MESTRE_EVENTO = E.COD_MESTRE_EVENTO
 AND OP.DATA_INICIO_PERIODO = E.DATA_INICIO_PERIODO
JOIN RHFP0401 ORG
  ON ORG.COD_ORGANOGRAMA = OP.COD_ORGANOGRAMA
WHERE ORG.COD_NIVEL2 IS NOT NULL
AND E.COD_CONTRATO = 145459
ORDER BY E.COD_CONTRATO, E.DATA_INICIO_PERIODO, E.DATA_INICIO_FERIAS, E.COD_EVENTO;





















